site_name: MonumentRecommendation
site_description: A rule-based recommendation system for monuments
site_author: Anoobee
repo_url: https://github.com/username/monumentrecommendation

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API Reference: api-reference.md
  - Database Schema: database.md
  - Docker Setup: docker-setup.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - tables
  - attr_list
  - def_list

plugins:
  - search
